"""ASVS catalog loader — rich metadata from build-time extracted JSON.

The catalog is parsed once from ``data/asvs_catalog.json`` (generated by
``scripts/extract_asvs_catalog.py``) and held in process memory via
``@lru_cache``. The consolidated skill calls ``enrich_finding()`` to
supplement per-requirement findings with catalog metadata.
"""

import json
import logging
from functools import lru_cache
from pathlib import Path
from typing import Any

_CATALOG_PATH = Path(__file__).parent / "data" / "asvs_catalog.json"

_log = logging.getLogger(__name__)


@lru_cache(maxsize=1)
def load_catalog() -> dict[str, dict[str, Any]]:
    """Load ASVS catalog from JSON. Cached after first call.

    Warns and returns {} if the JSON file is absent — the agent runs
    in degraded mode (empty catalog, no enrichment) rather than
    failing hard.
    """
    if not _CATALOG_PATH.exists():
        _log.warning(
            "ASVS catalog JSON missing at %s — running in degraded mode. "
            "Regenerate via scripts/extract_asvs_catalog.py.",
            _CATALOG_PATH,
        )
        return {}
    try:
        with _CATALOG_PATH.open() as f:
            return json.load(f)
    except json.JSONDecodeError as exc:
        _log.error(
            "ASVS catalog at %s is malformed (%s) — running in degraded mode.",
            _CATALOG_PATH, exc,
        )
        return {}


def get_requirement(req_id: str) -> dict[str, Any] | None:
    """Get a requirement entry by ASVS Shortcode (e.g. 'V3.4.1')."""
    return load_catalog().get(req_id)


def get_requirements_by_chapter(chapter_id: str) -> list[dict[str, Any]]:
    """Return all requirements belonging to a chapter (e.g. 'V3')."""
    return [
        e for e in load_catalog().values()
        if e.get("chapter_id") == chapter_id
    ]


def get_requirements_by_level(levels: list[int]) -> list[dict[str, Any]]:
    """Return requirements applicable at ANY of the given target levels."""
    target = max(levels) if levels else 3
    return [
        e for e in load_catalog().values()
        if is_applicable_at_level(e, target)
    ]


def is_applicable_at_level(req: dict[str, Any], target_level: int) -> bool:
    """Return True if ``req`` applies at ``target_level``.

    ASVS semantics: ``level`` field stores the LOWEST verification
    level at which the requirement applies. L=2 means applies at L2+L3.
    """
    return req.get("level", 3) <= target_level


def enrich_finding(finding: dict[str, Any], req_id: str) -> dict[str, Any]:
    """Merge catalog metadata into a finding dict (mutates in place).

    Adds ``cwe_ids``, ``level``, ``chapter_id``, ``chapter_name``,
    ``section_id``, ``section_name``, and fills empty ``description``
    with the requirement text.
    """
    entry = get_requirement(req_id)
    if not entry:
        return finding
    if not finding.get("description"):
        finding["description"] = entry.get("description", "")
    finding["cwe_ids"] = entry.get("cwe_ids", [])
    finding["level"] = entry.get("level")
    finding["chapter_id"] = entry.get("chapter_id", "")
    finding["chapter_name"] = entry.get("chapter_name", "")
    finding["section_id"] = entry.get("section_id", "")
    finding["section_name"] = entry.get("section_name", "")
    return finding


def build_catalog_context(req_ids: list[str], max_chars: int = 3000) -> str:
    """Build a compact catalog context string for LLM prompts.

    Provides the LLM with structured ASVS metadata for relevant
    requirements so it can cite req_ids in findings.
    """
    parts: list[str] = []
    total = 0
    for rid in req_ids:
        entry = get_requirement(rid)
        if not entry:
            continue
        line = (
            f"ASVS-{rid} [L{entry['level']}] {entry.get('chapter_name', '')} / "
            f"{entry.get('section_name', '')}\n"
            f"  {entry.get('description', '')[:200]}\n"
        )
        if total + len(line) > max_chars:
            break
        parts.append(line)
        total += len(line)
    return "\n".join(parts)
