"""CWE catalog loader — provides rich metadata from build-time extracted JSON.

The catalog is parsed once from ``data/cwe_catalog.json`` (generated by
``scripts/extract_cwe_catalog.py``) and held in process memory via
``@lru_cache``. Skills call ``enrich_finding()`` to supplement their
hand-crafted finding dicts with catalog descriptions and mitigations
without adding runtime network calls.

The enriched catalog (v4.19.1) includes detection methods, code examples,
related weakness graphs, keywords, and static detectability scores.
"""

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

_CATALOG_PATH = Path(__file__).parent / "data" / "cwe_catalog.json"


@lru_cache(maxsize=1)
def load_catalog() -> dict[str, dict[str, Any]]:
    """Load CWE catalog from JSON. Cached after first call."""
    if not _CATALOG_PATH.exists():
        return {}
    with _CATALOG_PATH.open() as f:
        return json.load(f)


def get_cwe(cwe_id: str) -> dict[str, Any] | None:
    """Get metadata for a CWE by numeric ID string (e.g. '89')."""
    return load_catalog().get(cwe_id)


@lru_cache(maxsize=1)
def _parent_children_index() -> dict[str, list[str]]:
    """Parent CWE ID -> direct ChildOf children (one hop). Cached."""
    idx: dict[str, list[str]] = {}
    for cid, e in load_catalog().items():
        seen_this: set[str] = set()
        for r in e.get("related_weaknesses", []):
            if r.get("nature") != "ChildOf":
                continue
            pid = r.get("cwe_id", "")
            if not pid or cid in seen_this:
                continue
            seen_this.add(cid)
            idx.setdefault(pid, []).append(cid)
    return idx


def get_descendants(cwe_id: str) -> list[str]:
    """Direct ChildOf children only (one hop). Grand-children excluded by design."""
    return _parent_children_index().get(cwe_id, [])


def get_static_detectable(min_score: float = 0.3) -> list[dict[str, Any]]:
    """Return all CWEs marked as static-analysis detectable above threshold.

    Args:
        min_score: Minimum static_detectability score (0.0-1.0).

    Returns:
        List of CWE entries sorted by static_detectability descending.
    """
    catalog = load_catalog()
    detectable = [
        entry for entry in catalog.values()
        if entry.get("static_detectability", 0) >= min_score
    ]
    detectable.sort(key=lambda e: -e.get("static_detectability", 0))
    return detectable


def get_by_keyword(keyword: str) -> list[dict[str, Any]]:
    """Find CWEs whose keywords match the given term.

    Args:
        keyword: Lowercase search term.

    Returns:
        List of matching CWE entries.
    """
    keyword = keyword.lower()
    catalog = load_catalog()
    return [
        entry for entry in catalog.values()
        if keyword in entry.get("keywords", [])
    ]


def get_related(cwe_id: str, nature: str = "") -> list[str]:
    """Get related CWE IDs for a given CWE.

    Args:
        cwe_id: Numeric CWE ID string.
        nature: Optional filter by relationship nature (ChildOf, ParentOf, etc.).

    Returns:
        List of related CWE ID strings.
    """
    entry = get_cwe(cwe_id)
    if not entry:
        return []
    related = entry.get("related_weaknesses", [])
    if nature:
        related = [r for r in related if r.get("nature") == nature]
    return [r["cwe_id"] for r in related]


def get_code_examples(cwe_id: str, nature: str = "bad") -> list[dict[str, str]]:
    """Get demonstrative code examples for a CWE.

    Args:
        cwe_id: Numeric CWE ID string.
        nature: 'bad' for vulnerable code, 'good' for fixed code.

    Returns:
        List of dicts with 'language' and 'code' keys.
    """
    entry = get_cwe(cwe_id)
    if not entry:
        return []
    return [
        ex for ex in entry.get("code_examples", [])
        if ex.get("nature") == nature
    ]


def enrich_finding(finding: dict[str, Any], cwe_id: str) -> dict[str, Any]:
    """Merge catalog metadata into a finding dict.

    Only fills empty ``description`` and ``recommendation`` fields — the
    hand-crafted skill messages always take precedence. Always adds
    ``cwe_name`` and ``cwe_likelihood`` as supplementary metadata.

    Args:
        finding: Finding dict from a skill check function.
        cwe_id: Numeric CWE ID string (e.g. '89', '787').

    Returns:
        The same finding dict, mutated in place with catalog data.
    """
    entry = get_cwe(cwe_id)
    if not entry:
        return finding
    if not finding.get("description"):
        finding["description"] = entry.get("description", "")
    if not finding.get("recommendation") and entry.get("mitigation"):
        finding["recommendation"] = entry["mitigation"]
    finding["cwe_name"] = entry.get("name", "")
    finding["cwe_likelihood"] = entry.get("likelihood", "")
    # Add static detectability confidence from catalog
    if entry.get("static_detectability"):
        finding["catalog_confidence"] = entry["static_detectability"]
    return finding


def build_catalog_context(cwe_ids: list[str], max_chars: int = 4000) -> str:
    """Build a compact catalog context string for LLM prompts.

    Provides the LLM with structured CWE metadata for relevant weaknesses
    so it can make informed detection decisions with catalog-grade accuracy.

    Args:
        cwe_ids: List of CWE IDs to include.
        max_chars: Maximum character budget.

    Returns:
        Formatted catalog context string.
    """
    parts: list[str] = []
    total = 0
    for cwe_id in cwe_ids:
        entry = get_cwe(cwe_id)
        if not entry:
            continue
        name = entry.get("name", "")
        desc = entry.get("description", "")[:150]
        likelihood = entry.get("likelihood", "")
        keywords = ", ".join(entry.get("keywords", [])[:8])
        line = f"CWE-{cwe_id}: {name}"
        if likelihood:
            line += f" [Likelihood: {likelihood}]"
        line += f"\n  {desc}"
        if keywords:
            line += f"\n  Keywords: {keywords}"
        examples = get_code_examples(cwe_id, "bad")
        if examples:
            ex = examples[0]
            snippet = ex["code"][:100].replace("\n", " ")
            line += f"\n  Bad example ({ex['language']}): {snippet}"
        line += "\n"
        if total + len(line) > max_chars:
            break
        parts.append(line)
        total += len(line)
    return "\n".join(parts)
