#!/usr/bin/env bash
#
# scripts/build-release.sh — produces one per-platform tarball for
# the native installer (feature 0044). Runs in CI's release matrix
# and locally for testing.
#
# Usage:
#   scripts/build-release.sh <version> <os> <arch>
#
# Example:
#   scripts/build-release.sh v0.1.0 linux amd64
#
# Output:
#   dist/vulture-<version>-<os>-<arch>.tar.gz
#   dist/SHA256SUMS  (appended)
#
# This script is shellcheck-clean.

set -euo pipefail

VERSION=${1:-}
OS=${2:-$(uname -s | tr '[:upper:]' '[:lower:]')}
ARCH=${3:-$(uname -m)}

if [ -z "$VERSION" ]; then
    echo "usage: $0 <version> [os] [arch]" >&2
    exit 1
fi
case "$ARCH" in
    x86_64) ARCH=amd64 ;;
    aarch64) ARCH=arm64 ;;
esac

REPO_ROOT=$(cd "$(dirname "$0")/.." && pwd)
DIST=$REPO_ROOT/dist
STAGE=$(mktemp -d)
TARBALL=$DIST/vulture-${VERSION}-${OS}-${ARCH}.tar.gz

mkdir -p "$DIST"

echo "==> Cross-compiling Go binary for ${OS}/${ARCH}"
mkdir -p "$STAGE/bin"
( cd "$REPO_ROOT/backend" && \
  GOOS="$OS" GOARCH="$ARCH" CGO_ENABLED=0 \
  go build -tags installmode -trimpath \
    -ldflags "-s -w -buildid= -X main.Version=${VERSION}" \
    -o "$STAGE/bin/vulture" ./cmd/vulture )

echo "==> Building frontend"
if [ -d "$REPO_ROOT/frontend/dist" ]; then
    echo "    using existing frontend/dist/"
else
    ( cd "$REPO_ROOT/frontend" && npm ci --silent && npm run build --silent )
fi
mkdir -p "$STAGE/runtime/frontend"
cp -r "$REPO_ROOT/frontend/dist/." "$STAGE/runtime/frontend/"

echo "==> Copying agents source"
mkdir -p "$STAGE/runtime/agents"
for agent in shared chaos_engineering owasp soc2 cwe xss ssdf asvs do178c discover prove; do
    [ -d "$REPO_ROOT/agents/$agent" ] || continue
    rsync -a --exclude='__pycache__' --exclude='.venv' --exclude='*.egg-info' \
        "$REPO_ROOT/agents/$agent" "$STAGE/runtime/agents/"
done

echo "==> Copying catalogs"
mkdir -p "$STAGE/runtime/catalogs"
if [ -f "$REPO_ROOT/agents/cwe/cwe_agent/data/cwe_catalog.json" ]; then
    cp "$REPO_ROOT/agents/cwe/cwe_agent/data/cwe_catalog.json" "$STAGE/runtime/catalogs/"
fi
if [ -f "$REPO_ROOT/agents/asvs/asvs_agent/data/asvs_catalog.json" ]; then
    cp "$REPO_ROOT/agents/asvs/asvs_agent/data/asvs_catalog.json" "$STAGE/runtime/catalogs/"
fi

echo "==> Generating requirements-frozen.txt (stub for local builds)"
# In CI this is generated by pip-compile --generate-hashes. For local
# builds we ship a per-agent requirements.txt aggregated into one file
# so install.sh's --require-hashes can be exercised offline.
{
    for req in "$REPO_ROOT"/agents/*/requirements.txt; do
        [ -f "$req" ] || continue
        cat "$req"
    done
} | sort -u > "$STAGE/runtime/agents/requirements-frozen.txt"

echo "==> Fetching python-build-standalone (vendored)"
# In CI this fetches from our own vendor-pbs release. For local dev we
# skip the bundled python and let install.sh fall back to system python.
PBS_NOTE="$STAGE/runtime/python/PBS_NOT_BUNDLED"
mkdir -p "$STAGE/runtime/python/bin"
cat > "$PBS_NOTE" <<EOF
This local-build tarball does NOT bundle python-build-standalone.
For production tarballs, CI fetches PBS from the vendor-pbs-* release
and extracts it here. Local installs from this tarball will rely on
the host's python3.12.
EOF

echo "==> Writing VERSION"
echo "$VERSION" > "$STAGE/VERSION"

echo "==> Building reproducible tarball"
# Reproducible: sorted, fixed mtime, no owners, gzip -n strips
# timestamp metadata.
( cd "$STAGE" && \
  tar --sort=name \
      --mtime='2020-01-01 00:00:00Z' \
      --owner=0 --group=0 --numeric-owner \
      -cf - . | gzip -9n > "$TARBALL" )

SHA=$(sha256sum "$TARBALL" | awk '{print $1}')
echo "${SHA}  $(basename "$TARBALL")" >> "$DIST/SHA256SUMS"

rm -rf "$STAGE"

echo ""
echo "==> Built $TARBALL ($(du -h "$TARBALL" | awk '{print $1}'))"
echo "    SHA256: $SHA"
