#!/usr/bin/env bash
#
# scripts/gen-lockfile.sh — feature 0055 B1.
# Generate the hashed agent-dependency lockfile (agents/requirements-frozen.txt)
# from the agents' pyproject.toml ranges. Third-party deps only: the first-party
# vulture-* packages load via PYTHONPATH and are never pip-installed, so they are
# stripped from the resolver input.
#
# Usage:
#   scripts/gen-lockfile.sh                 # lock to current in-range versions
#   scripts/gen-lockfile.sh --upgrade       # refresh all to latest in-range
#   scripts/gen-lockfile.sh --upgrade-pkg <name>
#
# Output is committed and reviewed; never hand-edit it. CI's check-lockfile.sh
# fails if the committed file is stale.
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"
OUT="agents/requirements-frozen.txt"

# Stable input path (NOT mktemp): uv records the input path in '# via -r <path>'
# provenance comments, so a random temp name makes the lockfile non-deterministic
# and breaks check-lockfile.sh. A fixed relative path keeps those comments stable.
mkdir -p build
IN="build/agent-deps.in"
TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

# 1. Aggregate every third-party requirement across all agent pyprojects,
#    dropping first-party 'vulture-*' deps (PYTHONPATH-loaded, never installed).
python3 - <<'PY' > "$IN"
import glob, tomllib
specs = {}
for f in sorted(glob.glob("agents/*/pyproject.toml")):
    data = tomllib.load(open(f, "rb"))
    for dep in data.get("project", {}).get("dependencies", []):
        name = dep.replace("[", " ").split()[0]
        for sep in (">", "<", "=", "~", "!", ";", " "):
            name = name.split(sep)[0]
        if not name.strip().lower().startswith("vulture-"):
            specs[dep] = None      # de-dup, preserve the spec
for s in specs:
    print(s)
PY

# 2. Resolve to a hash-pinned lockfile targeting the 3.12 floor. Prefer a single
#    universal lockfile; fall back to the host platform if universal can't resolve.
#    The constraint file (LLD 0055 B1a) marker-splits the few packages whose latest
#    version lacks a wheel on some target — currently cryptography on Intel macOS;
#    uv forks those into per-platform pins. It is the only hand-maintained lockfile
#    input, and check-lockfile.sh inherits it by calling this script.
CONSTRAINTS="agents/lockfile-constraints.txt"
UV_ARGS=(pip compile "$IN" --generate-hashes --no-header --quiet --python-version 3.12)
[ -f "$CONSTRAINTS" ] && UV_ARGS+=(--constraint "$CONSTRAINTS")
case "${1:-}" in
    --upgrade)     UV_ARGS+=(--upgrade) ;;
    --upgrade-pkg) UV_ARGS+=(--upgrade-package "${2:?--upgrade-pkg needs a name}") ;;
esac

if uv "${UV_ARGS[@]}" --universal -o "$TMP" 2>/dev/null; then
    MODE="universal"
else
    echo "warning: 'uv pip compile --universal' could not resolve; locking host platform only" >&2
    uv "${UV_ARGS[@]}" -o "$TMP"
    MODE="host-platform"
fi

{
    echo "# GENERATED by scripts/gen-lockfile.sh ($MODE) — DO NOT EDIT BY HAND."
    echo "# Regenerate with 'make freeze-deps' (then commit). Source of truth:"
    echo "# the agents' pyproject.toml dependency ranges (first-party vulture-*"
    echo "# packages are excluded; they load via PYTHONPATH)."
    cat "$TMP"
} > "$OUT"

echo "wrote $OUT — $(grep -c -- '--hash=' "$OUT") hash lines, mode=$MODE"
