#!/usr/bin/env bash
#
# Mode-B + Mode-D end-to-end smoke test.
#
# Brings up the full Vulture compose stack (Postgres + 9 agents + backend +
# frontend), bootstraps an admin + API key following the documented
# central_server_deployment.md procedure, and runs a tiny `vulture scan`
# from outside the docker network. Asserts the audit completes.
#
# Runnable both locally (developer machine) and from the
# .github/workflows/mode-b-e2e.yml workflow. The two paths use the exact
# same script so behavior in CI matches behavior on a laptop.
#
# Usage:
#   scripts/mode-b-smoke.sh             # full run; tear down at the end
#   scripts/mode-b-smoke.sh --keep      # leave the stack up for debugging
#
# Feature 0041.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# ---------------------------------------------------------------------------
# Args
# ---------------------------------------------------------------------------
KEEP=0
for arg in "$@"; do
    case "$arg" in
        --keep) KEEP=1 ;;
        -h|--help)
            sed -n '3,/^# Usage:/p; /^# Usage:/,/^$/p' "$0" | sed 's/^# \?//'
            exit 0
            ;;
        *)
            echo "unknown arg: $arg"
            exit 2
            ;;
    esac
done

# ---------------------------------------------------------------------------
# Logging helpers
# ---------------------------------------------------------------------------
RED='\033[0;31m'; GREEN='\033[0;32m'; BLUE='\033[0;34m'; NC='\033[0m'
log()  { echo -e "${BLUE}[smoke]${NC} $*"; }
ok()   { echo -e "${GREEN}[smoke]${NC} $*"; }
fail() { echo -e "${RED}[smoke]${NC} $*" >&2; }

cleanup() {
    local exit_code=$?
    if [[ $exit_code -ne 0 ]]; then
        fail "smoke failed (exit $exit_code); dumping recent compose logs:"
        (cd "$PROJECT_ROOT" && docker compose logs --tail=80 2>&1 | tail -200) || true
    fi
    if [[ $KEEP -eq 1 ]]; then
        log "leaving stack up (--keep)"
    else
        log "tearing down"
        (cd "$PROJECT_ROOT" && docker compose down -v --remove-orphans 2>/dev/null) || true
    fi
    exit $exit_code
}
trap cleanup EXIT

# ---------------------------------------------------------------------------
# Step 1: write a fresh .env (test-only secrets, no real ones)
# ---------------------------------------------------------------------------
ENV_FILE="$PROJECT_ROOT/.env"
log "writing test .env to $ENV_FILE"
cat > "$ENV_FILE" <<'EOF'
# Auto-generated by scripts/mode-b-smoke.sh — overwrites any existing .env.
# These are TEST-ONLY values, never use in any other context.

VULTURE_APP_NAME=vulture-smoke

# Ports
VULTURE_BACKEND_PORT=28080
VULTURE_FRONTEND_INTERNAL=23000
VULTURE_FRONTEND_HOST=23001
VITE_DEV_PORT=23000
VULTURE_POSTGRES_INTERNAL_PORT=25432
VULTURE_POSTGRES_HOST_PORT=25433

# Agent ports (default mapping)
VULTURE_AGENT_CHAOS_PORT=28001
VULTURE_AGENT_OWASP_PORT=28002
VULTURE_AGENT_SOC2_PORT=28003
VULTURE_AGENT_CWE_PORT=28004
VULTURE_AGENT_PROVE_PORT=28005
VULTURE_AGENT_XSS_PORT=28006
VULTURE_AGENT_SSDF_PORT=28007
VULTURE_AGENT_DISCOVER_PORT=28008
VULTURE_AGENT_DO178C_PORT=28009
VULTURE_AGENT_ASVS_PORT=28010

# Database
VULTURE_DB_MODE=postgres
VULTURE_DB_NAME=vulture
VULTURE_DB_USER=vulture
VULTURE_DB_PASSWORD=REDACTED-SMOKE-PW
VULTURE_DB_SSLMODE=disable

# Mode B settings
VULTURE_LOCAL_MODE=false
VULTURE_API_KEYS_ENABLED=true
VULTURE_USE_LLM=false
VULTURE_REQUIRE_LLM=false

# Auth (test-only secret; rotate for production)
VULTURE_JWT_SECRET=ci-mode-b-smoke-jwt-secret-not-for-production-use-only

# Source mount (read-only) — points at the project root so we can scan
# repo-internal fixtures.
VULTURE_SOURCE_DIR=./
EOF
ok ".env written"

# ---------------------------------------------------------------------------
# Step 2: bring the stack up
# ---------------------------------------------------------------------------
log "starting compose stack (this may take 1-5 min on first run)"
cd "$PROJECT_ROOT"

# Ensure the agent base image exists (compose builds agents FROM it).
if ! docker image inspect vulture-agent-base:latest >/dev/null 2>&1; then
    log "building vulture-agent-base:latest (one-time)"
    docker build -t vulture-agent-base:latest -f agents/Dockerfile.base agents/ >/dev/null
fi

# --wait blocks until all healthchecks pass; --wait-timeout caps the wait.
# COMPOSE_BAKE=false: the agents build FROM the locally-built
# vulture-agent-base:latest (above), which is never pushed to a registry.
# Compose's bake delegation builds via a buildx builder that does NOT share
# the daemon's image store, so it resolves `FROM vulture-agent-base:latest`
# as a registry pull and 403s ("pull access denied … docker.io/library/
# vulture-agent-base"). Forcing the classic daemon build path resolves the
# base from the local image store.
COMPOSE_BAKE=false docker compose up -d --build --wait --wait-timeout 600
ok "compose stack healthy"

# ---------------------------------------------------------------------------
# Step 3: confirm backend /health
# ---------------------------------------------------------------------------
log "checking backend /health"
for i in 1 2 3 4 5 6 7 8 9 10; do
    if curl -sf http://localhost:28080/health >/dev/null 2>&1; then
        break
    fi
    if [[ $i -eq 10 ]]; then
        fail "backend /health did not return 200 after 10 attempts"
        exit 1
    fi
    sleep 2
done
ok "backend /health returns 200"

# ---------------------------------------------------------------------------
# Step 4: bootstrap admin + API key
# ---------------------------------------------------------------------------
ADMIN_EMAIL="admin@ci-test.local"
ADMIN_PASS="smoke-test-password-1234"

log "registering admin user $ADMIN_EMAIL"
register_resp=$(curl -sf -X POST http://localhost:28080/api/auth/register \
    -H "Content-Type: application/json" \
    -d "{\"email\":\"$ADMIN_EMAIL\",\"password\":\"$ADMIN_PASS\",\"name\":\"Smoke Admin\"}" 2>&1) || {
    fail "register: $register_resp"
    exit 1
}
ok "admin registered"

# /api/auth/register sets role=member by Postgres CHECK constraint default
# (commit 7233c5f). The /api/api-keys endpoint requires role=admin
# (api_key_handler.go:121), so we need a manual promotion step. This
# mirrors the documented Mode-B bootstrap procedure (which currently
# omits this step — feature 0041 Phase 4 fixes the doc).
log "promoting $ADMIN_EMAIL to admin via psql"
docker compose exec -T postgres psql -U vulture -d vulture -p 25432 \
    -c "UPDATE users SET role='admin' WHERE email='$ADMIN_EMAIL';" >/dev/null
ok "admin promoted"

log "logging in to capture JWT"
login_resp=$(curl -sf -X POST http://localhost:28080/api/auth/login \
    -H "Content-Type: application/json" \
    -d "{\"email\":\"$ADMIN_EMAIL\",\"password\":\"$ADMIN_PASS\"}")
JWT=$(echo "$login_resp" | python3 -c "import json,sys;print(json.load(sys.stdin)['token'])")
if [[ -z "$JWT" || "$JWT" == "null" ]]; then
    fail "login did not return a token: $login_resp"
    exit 1
fi
ok "JWT acquired"

log "minting API key"
key_resp=$(curl -sf -X POST http://localhost:28080/api/api-keys \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $JWT" \
    -d '{"name":"smoke-test-key"}')
API_KEY=$(echo "$key_resp" | python3 -c "import json,sys;print(json.load(sys.stdin)['key'])")
if [[ -z "$API_KEY" || "$API_KEY" != vk_* ]]; then
    fail "api-key mint did not return a vk_xxx key: $key_resp"
    exit 1
fi
ok "API key: ${API_KEY:0:10}..."

# ---------------------------------------------------------------------------
# Step 5: build the CLI binary on the host
# ---------------------------------------------------------------------------
log "building CLI binary"
cd "$PROJECT_ROOT/cli"
go build -o /tmp/vulture-smoke-cli .
cd "$PROJECT_ROOT"
ok "CLI built: /tmp/vulture-smoke-cli"

# ---------------------------------------------------------------------------
# Step 6: scan a tiny fixture directory using the API key
# ---------------------------------------------------------------------------
SCAN_TARGET="agents/shared/shared/llm"
log "scanning fixture: $SCAN_TARGET (chaos type only)"

# IMPORTANT: do NOT pass --wait here. In the current backend design
# (stream_handler.go::runLiveAudit), agent dispatch is LAZY — it only
# happens when a client connects to /api/audits/<id>/stream. The
# CLI's --wait mode does polling-only and never opens that stream,
# so the audit sits in `pending` forever. The default (no --wait)
# path streams, which triggers dispatch correctly.
#
# Using `timeout` as a hard backstop in case agents hang or backend
# wedges. The chaos audit on this tiny fixture finishes in ~10-30s.
scan_output=$(timeout 180 /tmp/vulture-smoke-cli scan "$SCAN_TARGET" \
    --api-key "$API_KEY" \
    --server http://localhost:28080 \
    --types chaos \
    --no-cache 2>&1) || {
    fail "scan command failed or timed out (180s); raw output below"
    echo "$scan_output" | tail -40
    exit 1
}

# The CLI prints a truncated audit ID for display ("Audit started: <12-char>"),
# not the full UUID — using that in a URL fails Postgres' UUID parsing.
# Grab the most-recent audit's full ID via the listing API instead.
audits_json=$(curl -sf -H "Authorization: Bearer $API_KEY" \
    "http://localhost:28080/api/audits?limit=1" 2>&1) || {
    fail "could not fetch audit list"
    exit 1
}
audit_id=$(echo "$audits_json" | python3 -c "
import json,sys
d = json.load(sys.stdin)
items = d if isinstance(d, list) else d.get('audits', [])
print(items[0]['id'] if items else '')
" 2>/dev/null)
if [[ -z "$audit_id" ]]; then
    fail "no audits returned by /api/audits"
    exit 1
fi
ok "audit id: $audit_id"

# Now verify via the API that the audit actually completed.
final=$(curl -sf -H "Authorization: Bearer $API_KEY" \
    "http://localhost:28080/api/audits/$audit_id" 2>&1) || {
    fail "could not fetch final audit state"
    exit 1
}
final_status=$(echo "$final" | python3 -c "
import json,sys
print(json.load(sys.stdin).get('status', 'UNKNOWN'))
" 2>/dev/null)

if [[ "$final_status" != "completed" ]]; then
    fail "audit did not complete; status=$final_status"
    echo "----- final state -----"
    echo "$final" | python3 -m json.tool 2>&1 | head -40
    echo "-----------------------"
    exit 1
fi
ok "scan completed"

# ---------------------------------------------------------------------------
# Step 7: sanity-check audit list via the API key
# ---------------------------------------------------------------------------
log "verifying audit appears in /api/audits"
audits=$(curl -sf -H "Authorization: Bearer $API_KEY" http://localhost:28080/api/audits)
audit_count=$(echo "$audits" | python3 -c "
import json,sys
data = json.loads(sys.stdin.read())
items = data if isinstance(data, list) else data.get('audits', [])
print(len(items))
")
if [[ "$audit_count" -lt 1 ]]; then
    fail "expected at least one audit in /api/audits, got $audit_count"
    exit 1
fi
ok "/api/audits returns $audit_count audit(s)"

# ---------------------------------------------------------------------------
# All checks passed
# ---------------------------------------------------------------------------
ok "Mode-B + Mode-D smoke PASS"
