#!/usr/bin/env bash
#
# scripts/verify-no-secrets-in-logs.sh — CI lint that asserts no
# credential / JWT-secret literal appears in any file under
# data/logs/ of the smoke-install test. Run after smoke-install.sh
# but before publishing a release (see plan §"CI release pipeline").
#
# Strategy:
#   - capture the JWT secret generated by the smoke install
#   - grep every file in data/logs/ for that exact value
#   - also grep for common credential prefixes (sk-, sk-ant-, Bearer
#     eyJ) that smoke-install's test fixtures might use
#
# Exit non-zero on any hit.

set -euo pipefail

VULTURE_HOME=${VULTURE_HOME:-${1:-}}
if [ -z "$VULTURE_HOME" ] || [ ! -d "$VULTURE_HOME" ]; then
    echo "usage: VULTURE_HOME=/path/to/install $0" >&2
    echo "   or: $0 /path/to/install" >&2
    exit 2
fi

LOGS_DIR="$VULTURE_HOME/data/logs"
ENVFILE="$VULTURE_HOME/config/.env"

if [ ! -f "$ENVFILE" ]; then
    echo "info: no $ENVFILE; nothing to check"
    exit 0
fi

JWT=$(grep -E '^VULTURE_JWT_SECRET=' "$ENVFILE" | cut -d= -f2- || true)
if [ -z "$JWT" ]; then
    echo "info: no VULTURE_JWT_SECRET in env; nothing to check"
    exit 0
fi

FAIL=0

if [ -d "$LOGS_DIR" ]; then
    if grep -rqF "$JWT" "$LOGS_DIR" 2>/dev/null; then
        echo "FAIL: VULTURE_JWT_SECRET literal appears in $LOGS_DIR"
        FAIL=1
    fi
    # Common credential prefixes.
    for pat in 'sk-[A-Za-z0-9_]\{20,\}' 'sk-ant-[A-Za-z0-9_-]\{20,\}' 'Bearer eyJ[A-Za-z0-9._-]\+'; do
        if grep -rqE "$pat" "$LOGS_DIR" 2>/dev/null; then
            echo "FAIL: credential pattern $pat appears in $LOGS_DIR"
            FAIL=1
        fi
    done
fi

if [ "$FAIL" -ne 0 ]; then
    exit 1
fi

echo "verify-no-secrets-in-logs: PASS"
