"""The agent must understand the envelope the BROKER actually writes.

The fixture is generated by the Go side (broker/server/errors_upstream_test.go
:: TestBrokerEnvelopeFixtureIsCurrent) from real `writeErr` output. Nothing
here is hand-copied, because hand-copying is precisely how this feature failed
the first time: the agent helper was written against an envelope shape the
client SDK never produces, and thirteen unit tests passed while the function
returned "" for every real broker error in production.

If the Go envelope changes, that test rewrites this file and these tests fail
on the next run — which is the point. A green suite must mean the pass-through
still reaches the operator, not that both sides drifted together.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from shared.llm.errors import LLMErrorKind, broker_detail, llm_failure_message

FIXTURE = (
    Path(__file__).resolve().parents[4]
    / "backend"
    / "internal"
    / "broker"
    / "server"
    / "testdata"
    / "broker_404_envelope.json"
)


@pytest.fixture(scope="module")
def envelope() -> dict:
    assert FIXTURE.is_file(), (
        f"{FIXTURE} is missing. Regenerate it: "
        "cd backend && go test ./internal/broker/server/ -run BrokerEnvelopeFixture"
    )
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


class _SDKError(Exception):
    """openai's APIStatusError shape: `.body` is the UNWRAPPED inner object."""

    def __init__(self, body: dict) -> None:
        super().__init__(f"Error code: 404 - {body}")
        self.body = body


def test_the_real_envelope_is_recognised_as_ours(envelope: dict) -> None:
    detail = broker_detail(_SDKError(envelope["error"]))
    assert detail, (
        "the agent did not recognise the broker's OWN envelope as a broker error. "
        f"Envelope keys: {sorted(envelope['error'])}"
    )


def test_the_real_envelope_yields_the_rejected_model(envelope: dict) -> None:
    detail = broker_detail(_SDKError(envelope["error"]))
    upstream_msg = envelope["error"]["upstream"]["message"]
    assert upstream_msg[:40] in detail, (
        "the provider's own words did not survive to the operator-facing string, "
        f"which is the entire feature: {detail!r}"
    )
    assert "model_not_found" in detail


def test_the_wrapped_shape_works_too(envelope: dict) -> None:
    """A raw httpx/requests caller sees the envelope still wrapped in `error`."""
    assert broker_detail(_SDKError(envelope))


def test_the_persisted_degraded_reason_carries_it(envelope: dict) -> None:
    msg = llm_failure_message(LLMErrorKind.PROVIDER_BAD_REQUEST, _SDKError(envelope["error"]))
    assert "gemini-pro" in msg
    assert "not retriable" in msg, (
        "x_retriable:false is the difference between 'retry later' and 'fix your "
        f"config', and it is in the envelope: {msg!r}"
    )


def test_every_envelope_key_the_agent_relies_on_is_present(envelope: dict) -> None:
    """Names the contract explicitly, so a Go-side rename fails HERE with a
    readable message rather than as a mysteriously empty diagnosis."""
    err = envelope["error"]
    for key in ("code", "message", "x_retriable", "upstream"):
        assert key in err, f"the agent reads `{key}`; the broker no longer writes it"
    for key in ("provider", "status", "message"):
        assert key in err["upstream"], f"the agent reads `upstream.{key}`"
